name: buildx

on:
  push:
    branches: [master]
    paths-ignore:
      - .devcontainer
      - .github/workflows/dockerhub-description.yml
      - .vscode
      - .editorconfig
      - .gitattributes
      - .gitignore
      - .README.MD
    schedule:
      - cron: '0 0 * * 0'

jobs:
  buildx:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - base-image: python
            version: 3
          - base-image: python
            version: 3.6
          - base-image: python
            version: 3.7
          - base-image: python
            version: 3.8
          - base-image: python
            version: 3.9
          - base-image: java
            version: 8
          - base-image: java
            version: 11
          - base-image: rust
            version: 0-1
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up docker buildx
        id: buildx
        uses: docker/setup-buildx-action@v2.4.0
        with:
          version: latest

      - name: Login to DockerHub
        uses: docker/login-action@v2.0.0
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Run docker buildx
        run: |
          docker buildx build \
          -f Dockerfile \
          --target base \
          --progress plain \
          --platform linux/amd64 \
          --build-arg BUILD_DATE=`date -u +"%Y-%m-%dT%H:%M:%SZ"` \
          --build-arg VCS_REF=`git rev-parse --short HEAD` \
          --build-arg BASE_IMAGE=${{ matrix.base-image }} \
          --build-arg VERSION=${{ matrix.base-image }}-${{ matrix.version }} \
          --build-arg VARIANT=${{ matrix.version }} \
          -t klein2ms/base-devcontainer:${{ matrix.base-image }}-${{ matrix.version }} \
          --push \
          .
